name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 18.x
      uses: actions/setup-node@v1
      with:
        node-version: 18.x
    - name: npm install and build
      run: |
        npm ci
      env:
        CI: true
    - name: Debian package
      run: |
        echo $PWD
        sudo apt-get update -y
        sudo apt install -y build-essential fakeroot devscripts nodejs task-spooler npm debhelper
        debuild -uc -us
        mv ../tsp-web*.deb .
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Debian package
        path: |
          tsp-web*.deb
    - name: Semantic Release
      run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}