name: Workflow

on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  "nodejs":
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: npm
      - name: Install dependencies
        run: npm ci
        env:
          CI: true
      - name: Setup test environment
        run: |
          sudo apt-get update -y
          sudo apt install -y task-spooler
      - name: npm test
        run: npm test
  "debian-package":
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Debian package
        run: |
          sudo apt-get update -y
          sudo apt install -y build-essential fakeroot devscripts nodejs task-spooler npm debhelper
          debuild -uc -us
          mv ../tsp-web*.deb .
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Debian package
          path: |
            tsp-web*.deb
  "docker-build":
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  "semantic-release":
    runs-on: ubuntu-latest
    needs: ["nodejs", "debian-package", "docker-build"]
    permissions:
      contents: write
      packages: write
      pages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: npm
      - uses: actions/download-artifact@master
        with:
          name: Debian package
      - name: Install dependencies
        run: npm ci
      - name: Semantic Release
        run: npm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
