name: Workflow

on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: brunnerlivio/tsp-web

jobs:
  "build":
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'

      - name: Install dependencies
        run: make install

      - name: Build
        run: make build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: TSP Web
          path: |
            .bin/tsp-web
      
  "docker-build":
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

 
  "semantic-release":
    runs-on: ubuntu-latest
    needs: ["build", "docker-build"]
    permissions:
      contents: write
      packages: write
      pages: write
      id-token: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: npm
      - uses: actions/download-artifact@master
        with:
          name: Debian package
      - run: docker build --tag ${{ env.IMAGE_NAME }} .
      - name: Semantic Release
        run: npm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
